Models/Location.cs
namespace WHWebApp.Models
{
    public class Location
    {
        public int Id { get; set; }

        public string IdApi { get; set; }

        public string Name { get; set; }

        public Brewery Brewery { get; set; }

        public string StreetAddress { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        public string PostalCode { get; set; }

        public string Country { get; set; }

        public string PhoneNumber { get; set; }

        public string HoursOfOperation { get; set; }

        public string Website { get; set; }

        public string LocationType { get; set; }

        public string Latitude { get; set; }

        public string Longitude { get; set; }

        public string UserName { get; set; }

    }
}

ViewModels/LocationsViewModels/AddLocationViewModel.cs
using System.ComponentModel.DataAnnotations;
using WHWebApp.Models;

namespace WHWebApp.ViewModels.LocationsViewModels
{
    public class AddLocationViewModel
    {
         public Location Location { get; set; }
        
        public bool Success { get; set; }

        public string Message { get; set; }
        
        public string BreweryName { get; set; }
       
       [Required]
        public string LocationId { get; set; }

        public bool Post { get; set; }

        public string UserFirstName { get; set; }
    }
}

ViewModels/LocationsViewModels/DeleteLocationViewModel.cs
using System.ComponentModel.DataAnnotations;
using WHWebApp.Models;

namespace WHWebApp.ViewModels.LocationsViewModels
{
    public class DeleteLocationViewModel
    {
        public Location Location { get; set; }
        
        public bool Success { get; set; }

        public string Message { get; set; }
        
        public string BreweryName { get; set; }
       
       [Required]
        public string LocationId { get; set; }

        public bool Deleted { get; set; }

        public string UserFirstName { get; set; }
    }
}

ViewModels/LocationsViewModels/LocationInfoViewModel.cs
using WHWebApp.Models;

namespace WHWebApp.ViewModels.LocationsViewModels
{
    public class LocationInfoViewModel
    {
        public Location Location { get; set; }

        public string GoogleMapsSrc { get; set; }

        public bool Success { get; set; }

        public string Message { get; set; }
    }
}

ViewModels/LocationsViewModels/SearchLocationViewModel.cs
using WHWebApp.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WHWebApp.ViewModels.LocationsViewModels
{
    public class SearchLocationViewModel
    {
        [Required]
        public string SearchState { get; set; }

        public string SearchCity { get; set; }

        public List<Location> Locations { get; set; }

        public string Message { get; set; }

        public int PageNumber { get; set; }

        public int MaxPageNumber { get; set; }

        public bool Success { get; set; }
    }
}

Controllers/API/BeersController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.Data;
using WHWebApp.Models;

namespace WHWebApp.Controllers.API
{

    [Authorize]
    [Route("api/beers")]
    public class  BeersController : Controller
    {
        private ILogger _logger;
        private IAppRepository _repository;

        public BeersController(IAppRepository repository, 
        ILogger<BeersController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        
        //GET: api/beers
        //This method gets beer data from the db
        [HttpGet("")]
        public JsonResult Get()
        {
            var beers = _repository.GetUserBeers(User.Identity.Name);  

            var results = Mapper.Map<IEnumerable<Beer>>(beers);

            return Json(results);
        }

    }
}

Controllers/API/LocationInfoController.cs
using AutoMapper;
using WHWebApp.Data;
using WHWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Net;

namespace WHWebApp.Controllers.API
{
    [Authorize]
    [Route("api/location/{locationId}")]
    public class LocationInfoController : Controller
    {
        private ILogger _logger;
        private IAppRepository _repository;

        public LocationInfoController(IAppRepository repository,
        ILogger<LocationInfoController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        //GET: api/location/{locationId}
        //This method gets beer data from the db
        [HttpGet("")]
        public JsonResult Get(string locationId)
        {
            try
            {
                var id = Utilities.Extensions.SanitizeString(locationId);
                var location = _repository.GetLocationById(id, User.Identity.Name);

                var result = Mapper.Map<Location>(location);

                if (result == null)
                {
                    return Json(null);
                }

                return Json(result);
            }
            catch
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Error ocurred finiding the beer information");
            }
        }
    }
}

Controllers/API/LocationsController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.Data;
using WHWebApp.Models;

namespace WHWebApp.Controllers.API
{
    [Authorize]
    [Route("api/locations")]
    public class LocationsController : Controller
    {

        private ILogger _logger;
        private IAppRepository _repository;

        public LocationsController(ILogger<LocationsController> logger,
            IAppRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        //GET: api/locations
        [HttpGet("")]
        public JsonResult Get()
        {
            var locations = _repository.GetUserLocations(User.Identity.Name);

            var results = Mapper.Map<IEnumerable<Location>>(locations);

            return Json(results);
        }

    }
}

Controllers/Web/LocationsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.Models;
using WHWebApp.Services;
using WHWebApp.ViewModels.LocationsViewModels;
using WHWebApp.Utilities;
using WHWebApp.Data;
using System.Collections.Generic;
using System;

namespace WHWebApp.Controllers.Web
{
    [Authorize]
    public class LocationsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private ILogger _logger;
        private BeerApiService _beerApiService;
        private IAppRepository _repository;
        private MapsService _mapService;

        public LocationsController (UserManager<ApplicationUser> userManager,
        ILoggerFactory loggerFactory,
        BeerApiService beerApiService,
        IAppRepository repository,
        MapsService mapService)
        {
            _userManager = userManager;
            _logger = loggerFactory.CreateLogger<LocationsController>();
            _beerApiService = beerApiService;
            _repository = repository;
            _mapService = mapService;
        }

        //
        //GET: /Locations/Index
        [HttpGet]
        public async Task<IActionResult> Index(){            
            
            var user = await GetCurrentUserAsync();

            var viewModel = new IndexViewModel
            { 
                FirstName = Extensions.SanitizeString(user.FirstName)
            };
            
            return View(viewModel);
        }

        //
        //GET: /Locations/LocationInfo?LocationId=
        [HttpGet]
        public async Task<IActionResult> LocationInfo(string LocationId)
        {
            //If parameters are empty redirect to beers
            if (string.IsNullOrEmpty(LocationId))
            {
                return RedirectToAction(nameof(Index));
            }

            var locationId = Extensions.SanitizeString(LocationId);
            
            var breweryApiResult = await _beerApiService.GetLocation(locationId);

            var locationInfoViewModel = new LocationInfoViewModel
            {                
                Message = breweryApiResult.Message,
                Success = breweryApiResult.Success,
                Location = breweryApiResult.Location
            };
            var location = locationInfoViewModel.Location;
            locationInfoViewModel.GoogleMapsSrc = _mapService
                .GetMapSrc(location.Brewery.Name,location.StreetAddress,
                        location.City,location.State);
            
            return View(locationInfoViewModel);
        }

        //
        //GET: /Locations/AddLocation?LocationId=&BreweryName=
        [HttpGet]
        public IActionResult AddLocation(string LocationId, string BreweryName)
        {   
            var locationId = Extensions.SanitizeString(LocationId);
            var breweryName = Extensions.SanitizeString(BreweryName);
            
            var addLocationViewModel = new AddLocationViewModel()
            {
                LocationId = locationId,
                BreweryName = breweryName,
                Success = true,
                Message = $"Would you like to add {breweryName} to your locations?",
                Location = new Location(),
                Post = false
            };

            return View(addLocationViewModel);
        }

        //
        //POST: /Locations/AddLocation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLocation(AddLocationViewModel addLocationViewModel)
        {
            var locationId = Extensions.SanitizeString(addLocationViewModel.LocationId);

            var beerApiResult = await _beerApiService.GetLocation(locationId);

            addLocationViewModel.Success = beerApiResult.Success;
            addLocationViewModel.Message = beerApiResult.Message;
            addLocationViewModel.Location = beerApiResult.Location;
            addLocationViewModel.Post = true;
            addLocationViewModel.Location.UserName = User.Identity.Name;
            addLocationViewModel.BreweryName = addLocationViewModel.Location.Brewery.Name;            
                        
            if(!beerApiResult.Success)
            {
                return View(addLocationViewModel);
            }            
            var user = await GetCurrentUserAsync();
            addLocationViewModel.UserFirstName = user.FirstName;

            try
            {
                if(_repository.AddLocation(addLocationViewModel.Location,User.Identity.Name)
                    && _repository.SaveAll())
                {
                    addLocationViewModel.Message = $"{addLocationViewModel.BreweryName} was succesfully added!";
                    addLocationViewModel.Success = true;                   
                }
                else
                {
                    throw new Exception();
                }
            }
            catch
            {
                addLocationViewModel.Success = false;
                addLocationViewModel.Message = $"{addLocationViewModel.BreweryName} is already in your list or we had trouble adding it.";                
            }

            return View(addLocationViewModel);
        }

         //
        //GET: /Beers/DeleteBeer?BeerId=
        [HttpGet]
        public IActionResult DeleteLocation(string LocationId, string BreweryName)
        {
            var locationId = Extensions.SanitizeString(LocationId);
            var breweryName = Extensions.SanitizeString(BreweryName);

            var deleteLocationViewModel = new DeleteLocationViewModel()
            {
                LocationId = locationId,
                BreweryName = breweryName,
                Success = true,
                Message = $"Would you like to delete {breweryName} from your list?",
                Location = new Location(),
                Deleted = false
            };

            return View(deleteLocationViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLocation(DeleteLocationViewModel deleteLocationViewModel)
        {
            var locationId = Extensions.SanitizeString(deleteLocationViewModel.LocationId);
            var userName = User.Identity.Name;
            var breweryName = Extensions.SanitizeString(deleteLocationViewModel.BreweryName);

            deleteLocationViewModel.Success = _repository.DeleteLocation(locationId, userName);
            deleteLocationViewModel.Deleted = true;
            deleteLocationViewModel.BreweryName = breweryName;
            deleteLocationViewModel.LocationId = locationId;

            if (deleteLocationViewModel.Success)
            {
                deleteLocationViewModel.Message = $"{breweryName} was deleted succesfully from your list.";
            }
            else
            {
                deleteLocationViewModel.Message = $"{breweryName} is not in your list or we had trouble deleting it.";
            }

            var user = await GetCurrentUserAsync();
            deleteLocationViewModel.UserFirstName = user.FirstName;

            return View(deleteLocationViewModel);
        }

        //
        //GET: /Locations/SearchLocation
        [HttpGet]
        public async Task<IActionResult> SearchLocation(string city, StatesEnum enumState, string pagenum)
        {          
            var region = Extensions.GetRegion(enumState);
            var locality = Extensions.SanitizeString(city);
            
            int pageNumber;
            if(!int.TryParse(pagenum,out pageNumber))
            {
                pageNumber = 1;                
            }

            if(pageNumber < 1)
            {
                pageNumber = 1;
            }

            if (!string.IsNullOrEmpty(region))
            {                
                var locationsViewModel = new SearchLocationViewModel()
                {
                    SearchState = region,
                    SearchCity = locality,
                    Locations = new List<Location>()
                };
                
                var beerApiResult = await _beerApiService.GetLocations(region,locality,pageNumber);
                
                locationsViewModel.Message = beerApiResult.Message;
                locationsViewModel.PageNumber = beerApiResult.PageNumber;
                locationsViewModel.Success = beerApiResult.Success;
                locationsViewModel.MaxPageNumber = beerApiResult.MaxPageNumber;
                
                if (beerApiResult.Success)
                {                    
                    foreach (var location in beerApiResult.Locations)
                    {                       
                        locationsViewModel.Locations.Add(location);
                    }
                }               
                
                return View(locationsViewModel);
            }

            return RedirectToAction(nameof(Index));
        } 

        //
        //GET: /Beers/Index
        [HttpGet]

        #region Helpers

        //This method adds errors to the ModelState the data from the IdentityResult param
        //is passed to the ModelState Errors        
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion
    }
}

Views/Locations/AddLocation.cshtml
@model WHWebApp.ViewModels.LocationsViewModels.AddLocationViewModel

@section scripts{
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/js/app-locations.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/locationsController.js"></script>
    <script src="~/js/locationInfoController.js"></script>
}

@{
    var title = "Add Location Error!";

    if (Model.Success)
    {
        title = Model.BreweryName;
    }

    ViewBag.Title = title;
}

    <!-- Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                @ViewBag.Title <br />
                <small>
                    @Model.Message
                </small>
            </h2>                      
        </div>
    </div>
    <!-- /.row -->
@if(!Model.Post)
{
    <div class="row">
        <div class="col-xs-6">
            <form asp-controller="Locations" asp-action="AddLocation" method="post">
                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input name="LocationId" value="@Model.LocationId" hidden="true" />
                    <button type="submit" class="btn btn-success">Yes</button>
                    </div>
                </div>            
            </form>
        </div>
        <div class="col-xs-6">
            <a asp-asp-controller="Locations" asp-action="Index">
                <div class="btn btn-warning">No</div>
            </a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-xs-12">
            <a asp-asp-controller="Locations" asp-action="Index">
                <div class="btn btn-default">Return To My Locations</div>
            </a>
        </div>
    </div>

    <hr>   
    <div class="row" ng-app="app-locations">
        <div class="col-xs-12">
            <h3>@(Model.UserFirstName)'s Location List</h3>
        </div>
        <div ng-view></div>
    </div>
}

Views/Locations/DeleteLocation.cshtml
@model WHWebApp.ViewModels.LocationsViewModels.DeleteLocationViewModel

@section scripts{
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/js/app-locations.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/locationsController.js"></script>
    <script src="~/js/locationInfoController.js"></script>
}

@{
    var title = "Delete Location Error!";

    if (Model.Success)
    {
        title = Model.BreweryName;
    }

    ViewBag.Title = title;
}

    <!-- Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                @ViewBag.Title <br />
                <small>
                    @Model.Message
                </small>
            </h2>                      
        </div>
    </div>
    <!-- /.row -->
@if(!Model.Deleted)
{
    <div class="row">
        <div class="col-xs-6">
            <form asp-controller="Locations" asp-action="DeleteLocation" method="post">
                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input name="LocationId" value="@Model.LocationId" hidden="true" />
                    <input name="BreweryName" value="@Model.BreweryName" hidden="true" />
                    <button type="submit" class="btn btn-success">Yes</button>
                    </div>
                </div>            
            </form>
        </div>
        <div class="col-xs-6">
            <a asp-asp-controller="Locations" asp-action="Index">
                <div class="btn btn-warning">No</div>
            </a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-xs-12">
            <a asp-asp-controller="Locations" asp-action="Index">
                <div class="btn btn-default">Return To My Locations</div>
            </a>
        </div>
    </div>

    <hr> 
    <div class="row" ng-app="app-locations">
        <div class="col-xs-12">
            <h3>@(Model.UserFirstName)'s Locations List</h3>
        </div>
        <div ng-view></div>
    </div>
}

Views/Locations/Index.cshtml
@model WHWebApp.ViewModels.LocationsViewModels.IndexViewModel
@{
    ViewData["Title"] = "Favorite Locations";
}

@section Stylesheets {
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css">
}

<h2>@ViewData["Title"]</h2>

    <div class="row">
        <div class="col-xs-12">
            <h3>Search for breweries based on a location</h3>        
        </div>    
    </div>

<form asp-controller="Locations" asp-action="SearchLocation" method="get" class="form-horizontal">  
    <h4>Location Search:</h4>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="City" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="EnumState" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="selectpicker" asp-for="EnumState" 
                asp-items="Html.GetEnumSelectList<StatesEnum>()">
            </select>           
        </div>        
    </div>    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input name="PageNum" value="1" hidden="true" />
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </div>   
</form>
<hr>
<div ng-app="app-locations">
    <div ng-view></div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/js/app-locations.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/locationsController.js"></script>
    <script src="~/js/locationInfoController.js"></script>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
}

Views/Locations/LocationInfo.cshtml
@model WHWebApp.ViewModels.LocationsViewModels.LocationInfoViewModel
@{
    var title = string.Empty;

    if (Model.Success)
    {
        title = Model.Location.Brewery.Name;
    }
    else
    {
        title = "Error Finding Location";
    }

    ViewBag.Title = title;
}
    @if (!Model.Success)
    {
        <h3>@Model.Message</h3>
    }
    else
    {
        <br />
        <div class="row">
            <div class="col-xs-12 col-md-12 col-md-push-2 col-lg-10 col-lg-push-2">
                <img class="img-responsive undraggable" src="@Model.Location.Brewery.Banner" alt="@Model.Location.Brewery.Name" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-12">
                <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                    src="@Model.GoogleMapsSrc" allowfullscreen>
                </iframe>
            </div>
        </div>
        <br>
        <div class="well well-lg">
            <div class="row">
                <div class="col-xs-12">                
                    <h3>@Model.Location.Name</h3>
                    <hr>
                    <h4>Esablished: @Model.Location.Brewery.Established</h4>
                    @if(Model.Location.Website != "N/A")
                    {
                        <h4>Website: <a href="@Model.Location.Website" target="_blank">@Model.Location.Brewery.Name</a></h4>
                    }
                    <p>@Model.Location.Brewery.Description</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                @if(Model.Location.StreetAddress != "N/A")
                {
                    <h4>Address:</h4>
                    <p>
                        @Model.Location.StreetAddress
                        <br>
                        @(Model.Location.City != "N/A" ? Model.Location.City + ", " : "")
                        @(Model.Location.State != "N/A" ? Model.Location.State + ", ": "")
                        @(Model.Location.PostalCode != "N/A" ? Model.Location.PostalCode : "")
                        <br>
                        @(Model.Location.Country != "N/A" ? Model.Location.Country : "")
                    </p>
                }
                @if(Model.Location.PhoneNumber != "N/A")
                {
                    <p>
                        <i class="fa fa-phone"></i>
                        P: @Model.Location.PhoneNumber
                    </p>
                }
                
                </div>
                <div class="col-sm-6">
                @if(Model.Location.HoursOfOperation != "N/A")
                {
                    <h4>Hours:</h4>
                    <p>
                        @Model.Location.HoursOfOperation
                    </p>
                }
                @if(Model.Location.LocationType != "N/A")
                {
                    <h4>Type:</h4>
                    <p>
                        @Model.Location.LocationType
                    </p>
                }
                </div>
            </div> 
            <div class="row text-center">
                <div class="col-xs-6">
                    <a asp-asp-controller="Locations" asp-action="AddLocation" 
                        asp-route-locationid="@Model.Location.IdApi"
                        asp-route-breweryname="@Model.Location.Brewery.Name" 
                        class="btn btn-success">Add Location</a>
                </div>
                <div class="col-xs-6">
                    <a asp-controller="Beers" asp-action="Brewery" 
                        asp-route-breweryid="@Model.Location.Brewery.IdApi" 
                        class="btn btn-info">View Beers</a>
                </div>    
            </div>       
        </div>
    }