Models/Beer.cs
namespace WHWebApp.Models
{
    public class Beer
    {
        public int Id { get; set; }

        public string IdApi { get; set; }

        public string Name { get; set; }

        public string Abv { get; set; }
                
        public Style Style { get; set; }

        public string Label { get; set; }

        public string Icon { get; set; }

        public Brewery Brewery { get; set; }

        public string Description { get; set; }

        public string IsOrganic { get; set; }

        public string Ibu { get; set; }

        public Availability Availability { get; set; }

        public string GlassName { get; set; }
        
        public string UserName { get; set; }
    }
}

Models/Brewery.cs
namespace WHWebApp.Models
{
    public class Brewery
    {
        public int Id { get; set; }

        public string IdApi { get; set; }

        public string Name { get; set; }

        public string Image { get; set; }

        public string Banner { get; set; }

        public string Description { get; set; }

        public string Website { get; set; }

        public string Established { get; set; }
    }
}

ViewModels/BeersViewModels/AddBeerViewModel.cs
using System.ComponentModel.DataAnnotations;
using WHWebApp.Models;

namespace WHWebApp.ViewModels.BeersViewModels
{
    public class AddBeerViewModel
    {
        public Beer Beer { get; set; }
        
        public bool Success { get; set; }

        public string Message { get; set; }
        
        public string BeerName { get; set; }
       
       [Required]
        public string BeerId { get; set; }

        public bool Post { get; set; }

        public string UserFirstName { get; set; }
    }
}

ViewModels/BeersViewModels/BeerInfoViewModel.cs
using WHWebApp.Models;

namespace WHWebApp.ViewModels.BeersViewModels
{
    public class BeerInfoViewModel
    {
        public Beer Beer { get; set; }

        public bool Success { get; set; }

        public string Message { get; set; }
    }
}

ViewModels/BeersViewModels/BeerViewModel.cs
using System.ComponentModel.DataAnnotations;
using WHWebApp.Models;

namespace WHWebApp.Viewmodels.BeersViewModels
{
    public class BeerViewModel
    {
        public int Id { get; set; }

        [Required]
        public string IdApi { get; set; }
        
        public string Name { get; set; }

        public string Abv { get; set; }

        public Style Style { get; set; }

        public string Label { get; set; }

        public string Icon { get; set; }

        public Brewery Brewery { get; set; }

        public string Description { get; set; }

        public string IsOrganic { get; set; }

        public string Ibu { get; set; }

        public Availability Availability { get; set; }

        public string GlassName { get; set; }
    }
}

ViewModels/BeersViewModels/BreweryViewModel.cs
using WHWebApp.Models;
using System.Collections.Generic;

namespace WHWebApp.ViewModels.BeersViewModels
{
    public class BreweryViewModel
    {
        public Brewery Brewery { get; set; }

        public List<Beer> Beers { get; set; }

        public string Message { get; set; }

        public bool Success { get; set; }
    }
}

ViewModels/BeersViewModels/DeleteBeerViewModel.cs
using System.ComponentModel.DataAnnotations;
using WHWebApp.Models;

namespace WHWebApp.ViewModels.BeersViewModels
{
    public class DeleteBeerViewModel
    {
        public Beer Beer { get; set; }
        
        public bool Success { get; set; }

        public string Message { get; set; }
        
        public string BeerName { get; set; }
       
       [Required]
        public string BeerId { get; set; }

        public bool Deleted { get; set; }

        public string UserFirstName { get; set; }
    }
}

ViewModels/BeersViewModels/SearchBeerViewModel.cs
using WHWebApp.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WHWebApp.ViewModels.BeersViewModels
{
    public class SearchBeerViewModel
    {
        [Required]
        public string SearchName { get; set; }

        public List<Beer> Beers { get; set; }

        public string Message { get; set; }

        public int PageNumber { get; set; }

        public int MaxPageNumber { get; set; }

        public bool Success { get; set; }
    }
}

Controllers/API/BeerInfoController.cs
using System.Net;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.Data;
using WHWebApp.Models;

namespace WHWebApp.Controllers.API
{
    [Authorize]
    [Route("api/beer/{beerId}")]
    public class  BeerInfoController : Controller
    {
        private ILogger _logger;
        private IAppRepository _repository;

        public BeerInfoController(IAppRepository repository, 
        ILogger<BeerInfoController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        //GET: api/beer/{beerId}
        //This method gets beer data from the db
        [HttpGet("")]
        public JsonResult Get(string beerId)
        {
            try
            {
                var id = Utilities.Extensions.SanitizeString(beerId);
                var beer = _repository.GetBeerById(id,User.Identity.Name);  
                
                var result = Mapper.Map<Beer>(beer);

                if(result == null)
                {
                    return Json(null);
                }

                return Json(result);
            }
            catch
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Error ocurred finiding the beer information");
            }
        }

    }
}

Controllers/API/BeersController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.Data;
using WHWebApp.Models;

namespace WHWebApp.Controllers.API
{

    [Authorize]
    [Route("api/beers")]
    public class  BeersController : Controller
    {
        private ILogger _logger;
        private IAppRepository _repository;

        public BeersController(IAppRepository repository, 
        ILogger<BeersController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        
        //GET: api/beers
        //This method gets beer data from the db
        [HttpGet("")]
        public JsonResult Get()
        {
            var beers = _repository.GetUserBeers(User.Identity.Name);  

            var results = Mapper.Map<IEnumerable<Beer>>(beers);

            return Json(results);
        }

    }
}

Controllers/Web/BeersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHWebApp.ViewModels.BeersViewModels;
using System;
using WHWebApp.Models;
using WHWebApp.Services;
using WHWebApp.Data;
using WHWebApp.Utilities;

namespace WHWebApp.Controllers.Web
{
    [Authorize]
    public class BeersController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private ILogger _logger;
        private BeerApiService _beerApiService;
        private IAppRepository _repository;

        public BeersController(
        UserManager<ApplicationUser> userManager,
        ILoggerFactory loggerFactory,
        BeerApiService beerApiService,
        IAppRepository repository)
        {
            _userManager = userManager;
            _logger = loggerFactory.CreateLogger<BeersController>();
            _beerApiService = beerApiService;
            _repository = repository;
        }

        //
        //GET: /Beers/DeleteBeer?BeerId=
        [HttpGet]
        public IActionResult DeleteBeer(string BeerId, string BeerName)
        {
            var beerId = Extensions.SanitizeString(BeerId);
            var beerName = Extensions.SanitizeString(BeerName);

            var deleteBeerViewModel = new DeleteBeerViewModel()
            {
                BeerId = beerId,
                BeerName = beerName,
                Success = true,
                Message = $"Would you like to delete {beerName} from your list?",
                Beer = new Beer(),
                Deleted = false
            };

            return View(deleteBeerViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteBeer(DeleteBeerViewModel deleteBeerViewModel)
        {
            var beerId = Extensions.SanitizeString(deleteBeerViewModel.BeerId);
            var userName = User.Identity.Name;
            var beerName = Extensions.SanitizeString(deleteBeerViewModel.BeerName);

            deleteBeerViewModel.Success = _repository.DeleteBeer(beerId, userName);
            deleteBeerViewModel.Deleted = true;
            deleteBeerViewModel.BeerName = beerName;
            deleteBeerViewModel.BeerId = beerId;

            if (deleteBeerViewModel.Success)
            {
                deleteBeerViewModel.Message = $"{beerName} was deleted succesfully from your list.";
            }
            else
            {
                deleteBeerViewModel.Message = $"{beerName} is not in your list or we had trouble deleting it.";
            }

            var user = await GetCurrentUserAsync();
            deleteBeerViewModel.UserFirstName = user.FirstName;

            return View(deleteBeerViewModel);
        }

        //
        //GET: /Beers/AddBeer?BeerId=
        [HttpGet]
        public IActionResult AddBeer(string BeerId, string BeerName)
        {   
            var beerId = Extensions.SanitizeString(BeerId);
            var beerName = Extensions.SanitizeString(BeerName);
            
            var addBeerViewModel = new AddBeerViewModel()
            {
                BeerId = beerId,
                BeerName = beerName,
                Success = true,
                Message = $"Would you like to add {beerName} to your list?",
                Beer = new Beer(),
                Post = false
            };
                        
            return View(addBeerViewModel);
        }

        //
        //POST: /Beers/AddBeer?BeerId=
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBeer(AddBeerViewModel addBeerViewModel)
        {
            var beerId = Extensions.SanitizeString(addBeerViewModel.BeerId);

            var beerApiResult = await _beerApiService.GetBeerInformation(beerId);

            addBeerViewModel.Success = beerApiResult.Success;
            addBeerViewModel.Message = beerApiResult.Message;
            addBeerViewModel.Beer = beerApiResult.Beer;
            addBeerViewModel.Post = true;
            addBeerViewModel.Beer.UserName = User.Identity.Name;
            addBeerViewModel.BeerName = addBeerViewModel.Beer.Name;            
            
            
            if(!beerApiResult.Success)
            {
                return View(addBeerViewModel);
            }            
            var user = await GetCurrentUserAsync();
            addBeerViewModel.UserFirstName = user.FirstName;

            try
            {
                if(_repository.AddBeer(addBeerViewModel.Beer,User.Identity.Name)
                    && _repository.SaveAll())
                {
                    addBeerViewModel.Message = $"{addBeerViewModel.Beer.Name} was succesfully added!";
                    addBeerViewModel.Success = true;                   
                }
                else
                {
                    throw new Exception();
                }
            }
            catch
            {
                addBeerViewModel.Success = false;
                addBeerViewModel.Message = $"{addBeerViewModel.Beer.Name} is already in your list or we had trouble adding it.";                
            }

            return View(addBeerViewModel);
        }

        //
        //GET: /Beers/Index
        [HttpGet]
        public async Task<IActionResult> Index(){
            
            var user = await GetCurrentUserAsync();
            
            var viewModel = new IndexViewModel
            { 
                FirstName = Extensions.SanitizeString(user.FirstName)
            };
            
            return View(viewModel);
        }

        //
        //GET: /App/BeerInfo?BeerId=
        public async Task<IActionResult> BeerInfo(string BeerId)
        {
            if (string.IsNullOrEmpty(BeerId))
            {
                return RedirectToAction(nameof(Index));
            }

            var beerId = Extensions.SanitizeString(BeerId);

            var breweryApiResult = await _beerApiService.GetBeerInformation(beerId);

            var beerInfoViewModel = new BeerInfoViewModel
            {
                Message = breweryApiResult.Message,
                Success = breweryApiResult.Success,
                Beer = breweryApiResult.Beer
            };

            return View(beerInfoViewModel);
        }

        //
        //GET: /Beers/Beer
        public async Task<IActionResult> SearchBeer(string search,string pagenum)
        {
            if (string.IsNullOrEmpty(search) || string.IsNullOrEmpty(pagenum))
            {
                return RedirectToAction(nameof(Index));
            }

            var beerName = Extensions.SanitizeString(search);

            int pageNumber;
            if(!int.TryParse(pagenum,out pageNumber))
            {
                pageNumber = 1;                
            }

            if(pageNumber < 1)
            {
                pageNumber = 1;
            }

            if (beerName != string.Empty)
            {
                var beerViewModel = new SearchBeerViewModel()
                {
                    SearchName = beerName,                    
                    Beers = new List<Beer>()
                };

                var beerApiResult = await _beerApiService.GetBeers(beerName,pageNumber);

                beerViewModel.Message = beerApiResult.Message;
                beerViewModel.PageNumber = beerApiResult.PageNumber;
                beerViewModel.Success = beerApiResult.Success;
                beerViewModel.MaxPageNumber = beerApiResult.MaxPageNumber;
                
                if (beerApiResult.Success)
                {
                    foreach (var beer in beerApiResult.Beers)
                    {
                        beerViewModel.Beers.Add(beer);
                    }
                }

                return View(beerViewModel);
            }

            return RedirectToAction(nameof(Index));
        }      

        //
        //GET: /App/SarchBrewery
        public async Task<IActionResult> SearchBrewery(string search, string pagenum)
        {
            if (string.IsNullOrEmpty(search) || string.IsNullOrEmpty(pagenum))
            {
                return RedirectToAction(nameof(Index));
            }

            var breweryName = Extensions.SanitizeString(search);

            int pageNumber;
            if (!int.TryParse(pagenum, out pageNumber))
            {
                pageNumber = 1;
            }

            if(pageNumber < 1)
            {
                pageNumber = 1;
            }

            var breweryApiResult = await _beerApiService.GetBreweries(breweryName, pageNumber);

            var brewerySearchModel = new SearchBreweryViewModel()
            {
                SearchName = breweryName,
                MaxPageNumber = breweryApiResult.MaxPageNumber,
                Message = breweryApiResult.Message,
                PageNumber = breweryApiResult.PageNumber,
                Success = breweryApiResult.Success,
                Breweries = new List<Brewery>()
            };

            if (breweryApiResult.Success)
            {
                foreach(var brewery in breweryApiResult.Breweries)
                {
                    brewerySearchModel.Breweries.Add(brewery);
                }
            }

            return View(brewerySearchModel);
        }

         //
        //GET: /App/Brewery?BreweryId=
        public async Task<IActionResult> Brewery(string BreweryId)
        {
            if (string.IsNullOrEmpty(BreweryId))
            {
                return RedirectToAction(nameof(Index));
            }
            
            var breweryId = Extensions.SanitizeString(BreweryId);

            var breweryApiResult = await _beerApiService.GetBeersFromBrewery(breweryId);

            var breweryViewModel = new BreweryViewModel
            {
                Brewery = new Brewery(),

ViewComponents/PaginationViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WHWebApp.ViewModels.ViewComponentModels;

namespace WHWebApp.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int pageNumber, int maxPageNumber, string controller, string action, string searchName)
        {
            var paginationViewModel = new PaginationViewComponentModel
            {
                PageNumber = pageNumber,
                MaxPageNumber = maxPageNumber,
                Controller = controller,
                Action = action,
                SearchName = searchName
            };

            return View(paginationViewModel);
        }
    }
}

Views/Beers/AddBeer.cshtml
@model WHWebApp.ViewModels.BeersViewModels.AddBeerViewModel

@section scripts{
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/js/app-beers.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/beersController.js"></script>
    <script src="~/js/beerInfoController.js"></script>
    <script src="~/js/breweryInfoController.js"></script>
}

@{
    var title = "Add Beer Error!";

    if (Model.Success)
    {
        title = Model.BeerName;
    }

    ViewBag.Title = title;
}

    <!-- Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                @ViewBag.Title <br />
                <small>
                    @Model.Message
                </small>
            </h2>                      
        </div>
    </div>
    <!-- /.row -->
@if(!Model.Post)
{
    <div class="row">
        <div class="col-xs-6">
            <form asp-controller="Beers" asp-action="AddBeer" method="post">
                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input name="BeerId" value="@Model.BeerId" hidden="true" />
                    <button type="submit" class="btn btn-success">Yes</button>
                    </div>
                </div>            
            </form>
        </div>
        <div class="col-xs-6">
            <a asp-asp-controller="Beers" asp-action="Index">
                <div class="btn btn-warning">No</div>
            </a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-xs-12">
            <a asp-asp-controller="Beers" asp-action="Index">
                <div class="btn btn-default">Return To My Beer List Menu</div>
            </a>
        </div>
    </div>

    <hr>   
    <div class="row" ng-app="app-beers">
        <div class="col-xs-12">
            <h3>@(Model.UserFirstName)'s Beer List</h3>
        </div>
        <div ng-view></div>
    </div>
}

Views/Beers/BeerInfo.cshtml
@model WHWebApp.ViewModels.BeersViewModels.BeerInfoViewModel

@{
    var title = "Beer Information";

    if (Model.Success)
    {
        title = Model.Beer.Name;
    }

    ViewBag.Title = title;
}

@if (!Model.Success)
{
    <p>@Model.Message</p>
}
else
{
    <br />
    <div class="row">
        <div class="col-xs-12">
            <img class="img-responsive undraggable" src="@Model.Beer.Brewery.Banner" alt="@Model.Beer.Brewery.Name" />
        </div>
    </div>
    <hr />
    <!-- Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">
                @ViewBag.Title <br />
                <small>
                    @if (Model.Success)
                {
                        @Model.Beer.Brewery.Name
                    }
                </small>
            </h3>
            
        </div>
    </div>
    <!-- /.row -->
    
        <div class="well well-lg">
            <div class="row">
                <div class="col-sm-6">
                    <img src="@Model.Beer.Label" alt="@Model.Beer.Name" class="img-responsive undraggable" />
                </div>
                <div class="col-sm-6">

                    <h4>Description:</h4>
                    <p>@Model.Beer.Description</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs12">
                    <h3>Details:</h3>
                    <ul>
                        <li>ABV%: @(Model.Beer.Abv)@(Model.Beer.Abv == "N/A" ? "" : "%")</li>
                    </ul>
                    <ul>
                        <li>IBU: @Model.Beer.Ibu</li>
                    </ul>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-xs-12">
                    <a asp-controller="Beers" asp-action="AddBeer" asp-route-beerid="@Model.Beer.IdApi" asp-route-beername="@Model.Beer.Name">
                        <div class="btn btn-success">Add Beer</div>
                    </a>
                </div>
            </div>
        </div>

        <div class="row text-center">
        <div class="col-xs-6">
            <a asp-asp-controller="Beers" asp-action="Index">
                <div class="btn btn-default">My Beers</div>
            </a>
        </div>
        <div class="col-xs-6">
            <a asp-asp-controller="Beers" asp-action="Brewery" asp-route-breweryid="@Model.Beer.Brewery.IdApi">
                <div class="btn btn-info">Brewery Beers</div>
            </a>
        </div>
    </div>

}

Views/Beers/Brewery.cshtml
@model WHWebApp.ViewModels.BeersViewModels.BreweryViewModel

@{

    var title = string.Empty;

    if (Model.Success)
    {
        title = Model.Brewery.Name;
    }
    else
    {
        title = "Error Finding Brewery";
    }

    ViewBag.Title = title;
}
    @if (!Model.Success)
    {   <div class="row">
        <div class="col-xs-12">
            <h3>@Model.Message</h3>
        </div>
    </div>
    }
    else
    {
        <br />
        <div class="row">
            <div class="col-xs-12 col-md-12 col-md-push-2 col-lg-10 col-lg-push-2">
                <img class="img-responsive undraggable" src="@Model.Brewery.Banner" alt="@Model.Brewery.Name" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-12">
                <h3>
                    @Model.Brewery.Name
                </h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Style</th>
                            <th>ABV%</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var beer in Model.Beers)
                        {
                            <tr>
                                <td>@beer.Name</td>
                                <td>@beer.Style.ShortName</td>
                                <td>@(beer.Abv)@(beer.Abv == "N/A" ? "" : "%")</td>
                            </tr>
                            <tr>
                                <td>
                                    <img class="img-responsive undraggable" src="@beer.Icon" alt="@beer.Name" width="75" height="75" />
                                </td>
                                <td>
                                    <a asp-controller="Beers" asp-action="AddBeer" asp-route-beerid="@beer.IdApi" asp-route-beername="@beer.Name">
                                        <div class="btn btn-sm btn-success">
                                            Add Beer
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="Beers" asp-action="BeerInfo" asp-route-beerid="@beer.IdApi">
                                        <div class="btn btn-sm btn-info">
                                            More Info
                                        </div>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

Views/Beers/DeleteBeer.cshtml
@model WHWebApp.ViewModels.BeersViewModels.DeleteBeerViewModel

@section scripts{
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/js/app-beers.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/beersController.js"></script>
    <script src="~/js/beerInfoController.js"></script>
    <script src="~/js/breweryInfoController.js"></script>
}

@{
    var title = "Delete Beer Error!";

    if (Model.Success)
    {
        title = Model.BeerName;
    }

    ViewBag.Title = title;
}

    <!-- Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                @ViewBag.Title <br />
                <small>
                    @Model.Message
                </small>
            </h2>                      
        </div>
    </div>
    <!-- /.row -->
@if(!Model.Deleted)
{
    <div class="row">
        <div class="col-xs-6">
            <form asp-controller="Beers" asp-action="DeleteBeer" method="post">
                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input name="BeerId" value="@Model.BeerId" hidden="true" />
                    <input name="BeerName" value="@Model.BeerName" hidden="true" />
                    <button type="submit" class="btn btn-success">Yes</button>
                    </div>
                </div>            
            </form>
        </div>
        <div class="col-xs-6">
            <a asp-asp-controller="Beers" asp-action="Index">
                <div class="btn btn-warning">No</div>
            </a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-xs-12">
            <a asp-asp-controller="Beers" asp-action="Index">
                <div class="btn btn-default">Return To My Beer List Menu</div>
            </a>
        </div>
    </div>

    <hr> 
    <div class="row" ng-app="app-beers">
        <div class="col-xs-12">
            <h3>@(Model.UserFirstName)'s Beer List</h3>
        </div>
        <div ng-view></div>
    </div>
}

Views/Beers/SearchBeer.cshtml
@model WHWebApp.ViewModels.BeersViewModels.SearchBeerViewModel

@{
    ViewBag.Title = "Search for beer";
}
<div class="row">
    <div class="col-sm-12">
        <h2>@ViewBag.Title</h2>
        <h3>
            You search for
            <b>"@(Model.SearchName)"</b>
        </h3>
        <p>@Model.Message</p>
    </div>
</div>

@if (Model.Success)
{
    <hr />
    <div class="row">
        <div class="col-xs-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Brewey</th>
                        <th>Style</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var beer in Model.Beers)
                    {
                        <tr>
                            <td>@beer.Name</td>
                            <td>@beer.Brewery.Name</td>
                            <td>@beer.Style.ShortName</td>
                        </tr>
                        <tr>
                            <td>
                                <img class="img-responsive undraggable" src="@beer.Icon" alt="@beer.Name" width="75" height="75" />
                            </td>
                            <td>
                                <a asp-controller="Beers" asp-action="AddBeer" asp-route-beerid="@beer.IdApi" asp-route-beername="@beer.Name">
                                    <div class="btn btn-sm btn-success">Add Beer</div>
                                </a>
                            </td>
                            <td>
                                <a asp-controller="Beers" asp-action="BeerInfo" asp-route-beerid="@beer.IdApi">
                                    <div class="btn btn-sm btn-info">More Info</div>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>   

    @await Component.InvokeAsync("Pagination", new 
    { 
        pageNumber = @Model.PageNumber,
        maxPageNumber = @Model.MaxPageNumber,
        controller = "Beers",
        action = "SearchBeer",
        searchName = @Model.SearchName
    })             
}

Views/Beers/SearchBrewery.cshtml
@model WHWebApp.ViewModels.BeersViewModels.SearchBreweryViewModel

@{
    ViewBag.Title = "Search for brewery";
}

<h2>@ViewBag.Title</h2>
<h3>
    You search for
    <b>"@(Model.SearchName)"</b>
</h3>
<p>@Model.Message</p>

@if (Model.Success)
{
<hr />


<table class="table table-striped">
    <thead>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>View Beers</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var brewery in Model.Breweries)
        {
            <tr>
                <td><img class="img-responsive undraggable" src="@brewery.Image" alt="@brewery.Name" height="175" width="175"/></td>
                <td>@brewery.Name</td>
                <td>
                    <a asp-controller="Beers" asp-action="Brewery" asp-route-breweryid="@brewery.IdApi">
                        <div class="btn btn-sm btn-success">
                            View Beers
                        </div>
                    </a>
                </td>
            </tr>           
        }
    </tbody>
</table>

@await Component.InvokeAsync("Pagination", new 
    { 
        pageNumber = @Model.PageNumber,
        maxPageNumber = @Model.MaxPageNumber,
        controller = "Beers",
        action = "SearchBrewery",
        searchName = @Model.SearchName
    }) 

}